//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Create_Projects_Manager {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label project_name;
		
		protected System.Web.UI.WebControls.TextBox project_name_input;
		
		protected System.Web.UI.WebControls.Label startDate;
		
		protected System.Web.UI.WebControls.TextBox startDate_input;
		
		protected System.Web.UI.WebControls.Label endDate;
		
		protected System.Web.UI.WebControls.TextBox endDate_input;
		
		protected System.Web.UI.WebControls.Button Btn_CreateProject;
	}
}
