//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
    
    
    public partial class DefineTask_comments {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Label commentTitle;
        
        protected System.Web.UI.WebControls.TextBox commentTitle_in;
        
        protected System.Web.UI.WebControls.Button AddMore;
        
        protected System.Web.UI.WebControls.Button Finish;
    }
}
