//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class DefineTask_manager {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label project_name;
		
		protected System.Web.UI.WebControls.TextBox project_name_in;
		
		protected System.Web.UI.WebControls.Label task;
		
		protected System.Web.UI.WebControls.TextBox task_in;
		
		protected System.Web.UI.WebControls.Label deadline;
		
		protected System.Web.UI.WebControls.TextBox deadline_in;
		
		protected System.Web.UI.WebControls.Label description;
		
		protected System.Web.UI.WebControls.TextBox description_in;
		
		protected System.Web.UI.WebControls.Label regularEmployee;
		
		protected System.Web.UI.WebControls.TextBox regularEmployee_in;
		
		protected System.Web.UI.WebControls.Button DefineTask;
	}
}
