//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Review_Job_appliactions_manager {
		
		protected System.Web.UI.HtmlControls.HtmlForm Review_Job_appliactions_manager_form;
	}
}
