//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Business_Request {
		
		protected System.Web.UI.HtmlControls.HtmlForm Business_Requests;
		
		protected System.Web.UI.WebControls.Label lbl_replacement;
		
		protected System.Web.UI.WebControls.TextBox txt_replacement;
		
		protected System.Web.UI.WebControls.Label lbl_from_date;
		
		protected System.Web.UI.WebControls.TextBox txt_from_date;
		
		protected System.Web.UI.WebControls.Label lbl_to_date;
		
		protected System.Web.UI.WebControls.TextBox txt_to_date;
		
		protected System.Web.UI.WebControls.Label lbl_destination;
		
		protected System.Web.UI.WebControls.TextBox txt_destination;
		
		protected System.Web.UI.WebControls.Label lbl_purpose;
		
		protected System.Web.UI.WebControls.TextBox txt_purpose;
		
		protected System.Web.UI.WebControls.Button btn_apply_for_leave;
	}
}
