//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Profile {
		
		protected System.Web.UI.HtmlControls.HtmlForm info;
		
		protected System.Web.UI.WebControls.Label lbl_username;
		
		protected System.Web.UI.WebControls.TextBox txt_username;
		
		protected System.Web.UI.WebControls.Label lbl_password;
		
		protected System.Web.UI.WebControls.Button btn_changePass;
		
		protected System.Web.UI.WebControls.Label lbl_personal_email;
		
		protected System.Web.UI.WebControls.TextBox txt_personal_email;
		
		protected System.Web.UI.WebControls.Label lbl_first_name;
		
		protected System.Web.UI.WebControls.TextBox txt_first_name;
		
		protected System.Web.UI.WebControls.Label lbl_middle_name;
		
		protected System.Web.UI.WebControls.TextBox txt_middle_name;
		
		protected System.Web.UI.WebControls.Label lbl_last_name;
		
		protected System.Web.UI.WebControls.TextBox txt_last_name;
		
		protected System.Web.UI.WebControls.Label lbl_birth_date;
		
		protected System.Web.UI.WebControls.TextBox txt_birth_date;
		
		protected System.Web.UI.WebControls.Label lbl_age;
		
		protected System.Web.UI.WebControls.Label lbl_age_value;
		
		protected System.Web.UI.WebControls.Label lbl_years_of_exp;
		
		protected System.Web.UI.WebControls.TextBox txt_years_of_exp;
		
		protected System.Web.UI.WebControls.Button btn_update;
		
		protected System.Web.UI.WebControls.Label lbl_info_status;
		
		protected System.Web.UI.HtmlControls.HtmlForm Staff_Member;
		
		protected System.Web.UI.WebControls.Label lbl_shoutbox;
		
		protected System.Web.UI.WebControls.Button btn_check_in;
		
		protected System.Web.UI.WebControls.Button btn_check_out;
		
		protected System.Web.UI.WebControls.Button btn_check_attendance;
		
		protected System.Web.UI.WebControls.Button btn_leave_request;
		
		protected System.Web.UI.WebControls.Button btn_business_request;
		
		protected System.Web.UI.WebControls.Button btn_view_requests;
		
		protected System.Web.UI.WebControls.Button btn_send_email;
		
		protected System.Web.UI.WebControls.Button btn_view_emails;
		
		protected System.Web.UI.WebControls.Button btn_view_announcements;
		
		protected System.Web.UI.HtmlControls.HtmlForm Job_Seeker;
		
		protected System.Web.UI.HtmlControls.HtmlForm Manager;
		
		protected System.Web.UI.WebControls.Button btn_manager_approve_reject_requests;
		
		protected System.Web.UI.WebControls.Button btn_manager_Review_appliactions;
		
		protected System.Web.UI.WebControls.Button btn_manager_create_project;
		
		protected System.Web.UI.WebControls.Button btn_manager_assign_to_project;
		
		protected System.Web.UI.WebControls.Button btn_manager_remove_from_project;
		
		protected System.Web.UI.WebControls.Button btn_manager_define_task;
		
		protected System.Web.UI.WebControls.Button btn_manager_change_regularEmployee_task;
		
		protected System.Web.UI.WebControls.Button btn_manager_view_tasks;
		
		protected System.Web.UI.HtmlControls.HtmlForm HR_Employee;
		
		protected System.Web.UI.HtmlControls.HtmlForm Regular_Employee;
	}
}
