//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Register {
		
		protected System.Web.UI.HtmlControls.HtmlForm Register_Form;
		
		protected System.Web.UI.WebControls.Panel RegisterPanel;
		
		protected System.Web.UI.WebControls.Label lbl_username;
		
		protected System.Web.UI.WebControls.TextBox txt_username;
		
		protected System.Web.UI.WebControls.Label lbl_password;
		
		protected System.Web.UI.WebControls.TextBox txt_password;
		
		protected System.Web.UI.WebControls.Label lbl_password2;
		
		protected System.Web.UI.WebControls.TextBox txt_password2;
		
		protected System.Web.UI.WebControls.Label lbl_email;
		
		protected System.Web.UI.WebControls.TextBox txt_email;
		
		protected System.Web.UI.WebControls.Label lbl_first_name;
		
		protected System.Web.UI.WebControls.TextBox txt_first_name;
		
		protected System.Web.UI.WebControls.Label lbl_middle_name;
		
		protected System.Web.UI.WebControls.TextBox txt_middle_name;
		
		protected System.Web.UI.WebControls.Label lbl_last_name;
		
		protected System.Web.UI.WebControls.TextBox txt_last_name;
		
		protected System.Web.UI.WebControls.Label lbl_birthdate;
		
		protected System.Web.UI.WebControls.TextBox txt_birthdate;
		
		protected System.Web.UI.WebControls.Label lbl_experience;
		
		protected System.Web.UI.WebControls.TextBox txt_experience;
		
		protected System.Web.UI.WebControls.Button btn_register;
		
		protected System.Web.UI.WebControls.Label lbl_shoutbox;
	}
}
