//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Search_Jobs {
		
		protected System.Web.UI.HtmlControls.HtmlForm Search_Jobs_Form;
		
		protected System.Web.UI.WebControls.Label lbl_search;
		
		protected System.Web.UI.WebControls.TextBox txt_search;
		
		protected System.Web.UI.WebControls.Button btn_search;
	}
}
