//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class Send_Email {
		
		protected System.Web.UI.HtmlControls.HtmlForm Send_Email_Form;
		
		protected System.Web.UI.WebControls.Label lbl_recipient;
		
		protected System.Web.UI.WebControls.TextBox txt_recipient;
		
		protected System.Web.UI.WebControls.Label lbl_subject;
		
		protected System.Web.UI.WebControls.TextBox txt_subject;
		
		protected System.Web.UI.WebControls.Label lbl_body;
		
		protected System.Web.UI.WebControls.TextBox txt_body;
		
		protected System.Web.UI.WebControls.Button btn_send_email;
	}
}
