//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
	
	
	public partial class View_Emails {
		
		protected System.Web.UI.HtmlControls.HtmlForm View_Emails_Form;
		
		protected System.Web.UI.HtmlControls.HtmlForm Read_Email_Form;
		
		protected System.Web.UI.WebControls.Label lbl_sender;
		
		protected System.Web.UI.WebControls.Label lbl_sender_name;
		
		protected System.Web.UI.WebControls.Label lbl_subject;
		
		protected System.Web.UI.WebControls.Label lbl_subject_text;
		
		protected System.Web.UI.WebControls.Label lbl_body_text;
		
		protected System.Web.UI.WebControls.Button btn_back;
	}
}
