<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/Content/bootstrap.css">
<script src="/Scripts/jquery-3.2.1.js"></script>
<script src="/Scripts/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container" style="padding-top:0px;">
    <div class="navbar-header">
      <a class="navbar-brand" href="/Default.aspx"><img src="/images/Logo.png" width="100px" height="50px"></a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/Default.aspx">Home</a></li>
      <li><a href="/Profile.aspx">Profile</a></li>
      <li><a href="/Search_Jobs.aspx">Job Hunt</a></li>
      <li><a href="/View_Sorted_Companies.aspx">Company Sort</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/Logout.aspx">Logout</a></li>
    </ul>
  </div>
</nav>

<div class="container" style="margin-top:70px">
